#!/bin/sh
set -e

lb config noauto \
  --mode debian \
  --distribution bookworm \
  --archive-areas "main contrib non-free non-free-firmware" \
  --apt-recommends false \
  --apt-indices false \
  --debian-installer false \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash" \
  --bootloaders "grub-efi" \
  --linux-flavours amd64 \
  --memtest none \
  --system live \
  --updates true \
  --security true \
  --iso-application "so so not so tinyOS" \
  --iso-publisher "1234AAA4321qqq" \
  --iso-volume "SOSO_TINYOS" \
  --checksums sha256 \
  "${@}"